{
   "jobs" : {
      "build" : {
         "environment" : {
            "CIRCLE_ARTIFACTS" : "/tmp/circle-artifacts/build"
         },
         "machine" : {
            "image" : "ubuntu-2004:202101-01"
         },
         "steps" : [
            "checkout",
            {
               "run" : {
                  "command" : "mkdir -p $CIRCLE_ARTIFACTS"
               }
            },
            {
               "run" : {
                  "command" : "docker info"
               }
            },
            {
               "run" : {
                  "command" : "docker build -t quay.io/manakai/webhacc-old ."
               }
            },
            {
               "run" : {
                  "command" : "make test-deps"
               }
            },
            {
               "store_artifacts" : {
                  "path" : "/tmp/circle-artifacts/build"
               }
            },
            {
               "run" : {
                  "command" : "mkdir -p .ciconfigtemp/dockerimages/quay.io/manakai/"
               }
            },
            {
               "run" : {
                  "command" : "docker save -o .ciconfigtemp/dockerimages/quay.io/manakai/webhacc-old.tar quay.io/manakai/webhacc-old"
               }
            },
            {
               "persist_to_workspace" : {
                  "paths" : [
                     ".ciconfigtemp",
                     "deps",
                     "local",
                     "perl",
                     "prove",
                     "plackup",
                     "lserver",
                     "local-server",
                     "rev"
                  ],
                  "root" : "./"
               }
            }
         ]
      },
      "deploy_master" : {
         "machine" : {
            "image" : "ubuntu-2004:202101-01"
         },
         "steps" : [
            "checkout",
            {
               "attach_workspace" : {
                  "at" : "./"
               }
            },
            {
               "run" : {
                  "command" : "docker load -i .ciconfigtemp/dockerimages/quay.io/manakai/webhacc-old.tar"
               }
            },
            {
               "deploy" : {
                  "command" : "docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS quay.io || docker login -u $DOCKER_USER -p $DOCKER_PASS quay.io"
               }
            },
            {
               "deploy" : {
                  "command" : "docker push quay.io/manakai/webhacc-old"
               }
            },
            {
               "deploy" : {
                  "command" : "curl -sSf $BWALLER_URL | BWALL_GROUP=docker BWALL_NAME=quay.io/manakai/webhacc-old bash"
               }
            },
            {
               "deploy" : {
                  "command" : "make deploy-master"
               }
            }
         ]
      },
      "deploy_nightly" : {
         "machine" : {
            "image" : "ubuntu-2004:202101-01"
         },
         "steps" : [
            "checkout",
            {
               "attach_workspace" : {
                  "at" : "./"
               }
            },
            {
               "run" : {
                  "command" : "docker load -i .ciconfigtemp/dockerimages/quay.io/manakai/webhacc-old.tar"
               }
            },
            {
               "deploy" : {
                  "command" : "git rev-parse HEAD > head.txt\u000Acurl -f -s -S --request POST --header \u0022Authorization:token $GITHUB_ACCESS_TOKEN\u0022 --header \u0022Content-Type:application/json\u0022 --data-binary \u0022{\u005C\u0022base\u005C\u0022:\u005C\u0022master\u005C\u0022,\u005C\u0022head\u005C\u0022:\u005C\u0022`cat head.txt`\u005C\u0022,\u005C\u0022commit_message\u005C\u0022:\u005C\u0022auto-merge $CIRCLE_BRANCH into master\u005C\u0022}\u0022 \u0022https://api.github.com/repos/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/merges\u0022\u000Acurl -sSf $BWALLER_URL | BWALL_GROUP=merger.$CIRCLE_BRANCH BWALL_NAME=$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME bash"
               }
            }
         ]
      },
      "deploy_staging" : {
         "machine" : {
            "image" : "ubuntu-2004:202101-01"
         },
         "steps" : [
            "checkout",
            {
               "attach_workspace" : {
                  "at" : "./"
               }
            },
            {
               "run" : {
                  "command" : "docker load -i .ciconfigtemp/dockerimages/quay.io/manakai/webhacc-old.tar"
               }
            },
            {
               "deploy" : {
                  "command" : "git rev-parse HEAD > head.txt\u000Acurl -f -s -S --request POST --header \u0022Authorization:token $GITHUB_ACCESS_TOKEN\u0022 --header \u0022Content-Type:application/json\u0022 --data-binary \u0022{\u005C\u0022base\u005C\u0022:\u005C\u0022master\u005C\u0022,\u005C\u0022head\u005C\u0022:\u005C\u0022`cat head.txt`\u005C\u0022,\u005C\u0022commit_message\u005C\u0022:\u005C\u0022auto-merge $CIRCLE_BRANCH into master\u005C\u0022}\u0022 \u0022https://api.github.com/repos/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/merges\u0022\u000Acurl -sSf $BWALLER_URL | BWALL_GROUP=merger.$CIRCLE_BRANCH BWALL_NAME=$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME bash"
               }
            }
         ]
      },
      "test" : {
         "environment" : {
            "CIRCLE_ARTIFACTS" : "/tmp/circle-artifacts/test"
         },
         "machine" : {
            "image" : "ubuntu-2004:202101-01"
         },
         "steps" : [
            "checkout",
            {
               "attach_workspace" : {
                  "at" : "./"
               }
            },
            {
               "run" : {
                  "command" : "docker load -i .ciconfigtemp/dockerimages/quay.io/manakai/webhacc-old.tar"
               }
            },
            {
               "run" : {
                  "command" : "mkdir -p $CIRCLE_ARTIFACTS"
               }
            },
            {
               "run" : {
                  "command" : "make deps"
               }
            },
            {
               "run" : {
                  "background" : true,
                  "command" : "./plackup -p 5114 -t Twiggy::Prefork bin/server.psgi"
               }
            },
            {
               "run" : {
                  "command" : "sleep 10"
               }
            },
            {
               "run" : {
                  "command" : "curl -f http://localhost:5114"
               }
            },
            {
               "store_artifacts" : {
                  "path" : "/tmp/circle-artifacts/test"
               }
            }
         ]
      },
      "test-pmbp" : {
         "environment" : {
            "CIRCLE_ARTIFACTS" : "/tmp/circle-artifacts/test-pmbp"
         },
         "machine" : {
            "image" : "ubuntu-2004:202101-01"
         },
         "steps" : [
            "checkout",
            {
               "attach_workspace" : {
                  "at" : "./"
               }
            },
            {
               "run" : {
                  "command" : "docker load -i .ciconfigtemp/dockerimages/quay.io/manakai/webhacc-old.tar"
               }
            },
            {
               "run" : {
                  "command" : "mkdir -p $CIRCLE_ARTIFACTS"
               }
            },
            {
               "run" : {
                  "command" : "make test"
               }
            },
            {
               "store_artifacts" : {
                  "path" : "/tmp/circle-artifacts/test-pmbp"
               }
            }
         ]
      }
   },
   "version" : 2,
   "workflows" : {
      "build" : {
         "jobs" : [
            {
               "build" : {
               }
            },
            {
               "test-pmbp" : {
                  "requires" : [
                     "build"
                  ]
               }
            },
            {
               "test" : {
                  "requires" : [
                     "build"
                  ]
               }
            },
            {
               "deploy_master" : {
                  "context" : [
                     "deploy-context",
                     "deploy-context-manakai"
                  ],
                  "filters" : {
                     "branches" : {
                        "only" : [
                           "master"
                        ]
                     }
                  },
                  "requires" : [
                     "build",
                     "test-pmbp",
                     "test"
                  ]
               }
            },
            {
               "deploy_nightly" : {
                  "context" : [
                     "deploy-context",
                     "deploy-context-manakai"
                  ],
                  "filters" : {
                     "branches" : {
                        "only" : [
                           "nightly"
                        ]
                     }
                  },
                  "requires" : [
                     "build",
                     "test-pmbp",
                     "test"
                  ]
               }
            },
            {
               "deploy_staging" : {
                  "context" : [
                     "deploy-context",
                     "deploy-context-manakai"
                  ],
                  "filters" : {
                     "branches" : {
                        "only" : [
                           "staging"
                        ]
                     }
                  },
                  "requires" : [
                     "build",
                     "test-pmbp",
                     "test"
                  ]
               }
            }
         ]
      },
      "version" : 2
   }
}
